### ISSUE TITLE
Calculation of feature similarity & label similarity

### ISSUE THREAD

**Issue by joinling** [YingtongDou/CARE-GNN#14]
I used your code to calculate the feature similarity and label similarity for Yelp and Amazon. After setting the mode to 'all', the calculated value is different from what you wrote in your paper. For example, the feature similarity calculation value of Yelp in the R-U-R relationship is 0.99007332, while the paper writes 0.83.
May I ask if there was an error in my calculation?

**Comment by YingtongDou** [comment]
The result in the paper is wrong. Please read the updated similarity table in the readme.
