### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by stupidoge** [YingtongDou/CARE-GNN#16]
Hi, the Yelp dataset has four types elements.
```
 'homo': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
 	with 7693958 stored elements in Compressed Sparse Column format>,
 'net_rur': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
 	with 98630 stored elements in Compressed Sparse Column format>,
 'net_rtr': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
 	with 1147232 stored elements in Compressed Sparse Column format>,
 'net_rsr': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
```

I understand that `net_rur`, `net_rtr`, and `net_rsr` are metapath-based neighbors, which are created from the big and whole heterogeneous graph. However, for `homo` how to get that? Because I plan to use my own heterogeneous graph dataset, I just try to create metapath-based neighbors to replace those elements.

Thanks and best regards.

**Comment by YingtongDou** [comment]
The homo graph is created by combining the edges from the three following heterogeneous graphs and removing the duplicated ones.

**Comment by stupidoge** [comment]
got that. thanks.

**Comment by stupidoge** [comment]
@YingtongDou Hi author, I still have one question. If you are using a sparse matrix then use your function `sparse_to_adjlist()`, it will account for most of the memory because a sparse matrix is really memory-consuming. Especially, when I am using a really huge graph with more than 5 million nodes for each of 10 entities, everytime I try to transfer the whole heterogenous graph into homo based in metapath, and then use your function. The memory will kill my python porgram.

How to solve that? Do you have any suggestions?

**Comment by YingtongDou** [comment]
@stupidoge

Three suggested solutions:

- Pre-sample the neighbors of the nodes and store them in adjlist format before using CARE-GNN.

- Load the data with DGL and use the CARE-GNN DGL [example](https://github.com/dmlc/dgl/tree/master/examples/pytorch/caregnn). 

- Replace the GNN module with [PyG GNN module](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.models.GraphSAGE.html?highlight=graphsage) and leverage the [sparse matrix loader](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.from_scipy_sparse_matrix) and [PyG data object](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.data.Data.html#torch_geometric.data.Data) to handle the data.
