### ISSUE TITLE
musical_reviews.pickle file missing

### ISSUE THREAD

**Issue by ponywisethewisest** [YingtongDou/CARE-GNN#18]

**Comment by YingtongDou** [comment]
Please contact Prof. Julian McAuley@UCSD to access the old Amazon product data with helpfulness votes information. Once you get access, you can download the `json.gz` review data for Musical Instruments and run the given `amazon_preprocess.py`  to get the sampled 11949 nodes and their features. Alternatively, you can generate similar graphs using other sampled data from the Amazon dataset.
