### ISSUE TITLE
How did you represent the review node features in the Yelp dataset?

### ISSUE THREAD

**Issue by jhliu17** [YingtongDou/CARE-GNN#2]
Hi,

I try to read the code to understand the methodology in your paper. I am wondering how did you extract the review text feature as the node representation in the Yelp dataset? I have seen the node feature dimension used in it is  32. What is the meaning of each dimension?

Sincerely,
Raion

**Comment by YingtongDou** [comment]
Thanks for your interest in our paper!

We use handcrafted features for both Yelp and Amazon datasets. The Yelp feature comes from Table 2 of the following paper:

Shebuti Rayana, Leman Akoglu. Collective Opinion Spam Detection: Bridging Review Networks and Metadata. KDD 2015. 

We concatenate 15 review behavior&text features, 9 user behavior features, and 8 product behavior features of a review as a 32-dimension feature vector.

We have verified that text embeddings are almost useless for the Yelp spam review classification task, but they might work on your own dataset, you can have a try.

**Comment by jhliu17** [comment]
Thanks for your quick response 👍~! Would you please to release the pre-processing script used in the yelp dataset? I wanna have a try on my own dataset.  It will be more convenient for me to adapt the pre-processing procedure to my dataset.

**Comment by YingtongDou** [comment]
The python code for computing behavior features is [yelpFeatureExtraction.py](https://github.com/YingtongDou/Nash-Detect/blob/master/Utils/yelpFeatureExtraction.py).

You can [contact](http://odds.cs.stonybrook.edu/yelpchi-dataset/) the Yelp dataset author for the Matlab code to compute text features.

**Comment by haophancs** [comment]
Hi, I have seen the node feature dimension used in the Amazon dataset is 25. Could you please explain the structure of the dimensions?
