### ISSUE TITLE
Question in Metrics

### ISSUE THREAD

**Issue by SongRb** [YingtongDou/CARE-GNN#4]
https://github.com/YingtongDou/CARE-GNN/blob/411f726169cdef10da6306bc41b2aa2382aaeaa0/utils.py#L198-L211

Hey, may I know why the code outputs "GNN AUC" and "Label" in test phase? Which one is used in Table 3? 

![image](https://user-images.githubusercontent.com/15308237/96336516-f674b980-10b2-11eb-85b5-db4b9c1ca308.png)

**Comment by YingtongDou** [comment]
The GNN results are used in Table 3. The Label represents the classification results solely based on the label predictor.
