### ISSUE TITLE
Question about CARE-Weight Relation weight normalization

### ISSUE THREAD

**Issue by SongRb** [YingtongDou/CARE-GNN#5]
It seems that the softmax function is applied in embed_size dimension, not the relation dimension.

https://github.com/YingtongDou/CARE-GNN/blob/411f726169cdef10da6306bc41b2aa2382aaeaa0/layers.py#L386

**Comment by YingtongDou** [comment]
Hi,

Thanks for finding this issue! I will update the code later.

With the new softmax, the CARE-weight will have better performance, and the relation weight values are more reasonable.

If you find any other interesting issues, please feel free to point it out. I appreciate it a lot!
