### ISSUE TITLE
can't seem to run "python train.py"

### ISSUE THREAD

**Issue by furycurry** [YingtongDou/CARE-GNN#8]
When I am trying to run `python train.py` in the terminal, there is an error telling 
`mat1 and mat2 shapes cannot be multiplied (64x1024 and 64x2)`.
I am using **Jupyter Notebook** and have successfully downloaded and installed all the prerequisites for the code to run.

Here is also a screenshot of the error. 
![issue](https://user-images.githubusercontent.com/58500422/150575455-09552a83-f0db-4078-af15-cbcfb149ed12.png)

@YingtongDou

**Comment by YingtongDou** [comment]
The shape of the first matrix should be 1024 x 64 (batch_size x emb_size), please check your code and make sure the GNN output has the above shape.

**Comment by zerjilor** [comment]
same problem. just modified the shape of mat1 using torch.t, but the training result had little classification performance.

**Comment by zerjilor** [comment]
same problem. just modified the shape of mat1 using torch.t, but the training results had little classification performance. looks like the code needs to be fixed.

**Comment by kayzliu** [comment]
Sorry for the inconvenience. The problems are fixed in the last update #9. If there are any further questions, please don't hesitate to contact us.

**Comment by furycurry** [comment]
> same problem. just modified the shape of mat1 using torch.t, but the training results had little classification performance. looks like the code needs to be fixed.

Thanks
